#!/bin/bash
if [[ $(git remote -v | grep github.com) ]]; then
  exit 0
fi

MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"
export COMMIT_REGEX='^(SCD-[0-9]+:|Merge) .+'
export ERROR_MSG="Commit message format must match regex \"${COMMIT_REGEX}\""
if [[ $FILE_CONTENT =~ $COMMIT_REGEX ]]; then
  echo "Commit naming conventions: OK"
else
  echo "Commit naming conventions: FAILED"
  echo $ERROR_MSG
  exit 1
fi
