#!/bin/bash
if [[ $(git remote -v | grep github.com) ]]; then
  echo "Commit rules NOT enforced"
  exit 0
else
  echo "Commit rules enforced"  
fi

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
if [[ $BRANCH == "HEAD" ]]; then
  echo "Currently in detached state, skipping branch check"
  exit 0
fi
REGEX='^Sprint-[0-9]{4,}-[0-9]{2,}/SCD-[0-9]+'
export ERROR_MSG="Branch name format must match regex \"${REGEX}\""
if [[ $BRANCH =~ $REGEX ]]; then
    echo "Branch naming conventions: OK"
else
    echo "Warning: invalid branch name!"
    echo $ERROR_MSG
fi
